---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/index.mdx
  label: Home Page
- type: document
  path: content/tutorials/index.md
  label: Tutorial Page
- type: directory
  path: content/docs
  label: Docs
  create: all
  match: "**/*"
  new_doc_ext: mdx
- type: directory
  path: content/tutorials
  label: Tutorials
  create: all
  match: "**/*"
  new_doc_ext: mdx
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
